micronaut:
   application:
      name: micronautMongodbCrud
mongodb.uri: mongodb://localhost:27017

micronaut:
  server:
    port: 8081
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http://localhost:8080